sudo: disable
language: rust
rust:
  - stable
  - beta
  - nightly
os: 
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all